apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
  labels:
    {{- include "rana-flask.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
