apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
    {{- include "rana-flask.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 5000
      targetPort: 5000
