name: Build and Deploy Flask App

on:
  workflow_dispatch:  

env:
  ACR_NAME: ${{ vars.ACR_NAME }}     
  IMAGE_NAME: rana-flaskapp           
  IMAGE_TAG: rana                    
  RELEASE_NAME: rana-flask

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Building Docker image: $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG"
          docker build -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          echo "Pushing image to: $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG"
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Set kubeconfig from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

      - name: Test Kubernetes connection
        run: kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Deploy Helm chart
        run: |
          helm upgrade --install $RELEASE_NAME . \
            --set image.repository=$ACR_NAME/$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG \
            --set replicaCount=2
