name: Build and Deploy Flask App

on:
  workflow_dispatch: 


env:
  ACR_NAME: ${{ vars.ACR_NAME }}  
  IMAGE_NAME: Rana-FlaskApp
  IMAGE_TAG: rana
  RELEASE_NAME: rana-flask

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG .

      # Login to Azure Container Registry
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image to ACR
      - name: Push Docker image
        run: docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      # Authenticate to AKS using kubeconfig secret
      - name: Set kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      # Deploy using Helm
      - name: Deploy Helm chart
        run: |
          helm upgrade --install $RELEASE_NAME ./flask-kubernetes-chart \
            --set image.repository=$ACR_NAME/$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG \
            --set replicaCount=2
